description: >
  Fast, responsive, flexible, modular, FOSS and feature-rich Hugo Bootstrap Framework.

hb:
  styles:
    primary: "#7952b3"
  # debug: true
  logo: images/logo.svg
  announcement_bar:
    interval: 2500
  background_image:
    brightness: 20
  contact:
    endpoint: https://formspree.io/f/mnqyewwz
    recaptcha_sitekey: 6Lf12rImAAAAAB0v75Amp-4Y1QDTFM9Oq9d6me8w
  header:
    breakpoint: lg
    sticky: true
    full_width: true
    # theme: 'classic'
    # logo_bg: '#7952b3'
    # menus_alignment: 'end'
    brand: 'HB'
    socials:
      github: hbstack
      kofi: razonyang
      paypal: razonyang
      # twitter: razonyang
      # mastodon: razonyang
      rss: true
  blog:
    post_thumbnail_default: /images/thumbnail.jpg
    home:
      main_sections:
        - blog
        - docs
        - news
        - modules
    paginate: 30
    giscus:
      repo: hbstack/site
      repo_id: R_kgDOJLvAsw
      category: General
      category_id: DIC_kwDOJLvAs84CVBSG
      mapping: og:title
    utterances:
      repo: hbstack/site
    twikoo:
      env_id: https://twikoo.hugomods.com/
    sidebar:
      posts:
        style: pills
      taxonomies:
        style: underline
      profile:
        company: "[HB STACK](https://hbstack.dev/)"
        location: Internet
        socials:
          github: hbstack
          paypal: razonyang
          kofi: razonyang
          rss: true
  docs:
    giscus:
      repo: hbstack/site
      repo_id: R_kgDOJLvAsw
      category: General
      category_id: DIC_kwDOJLvAs84CVBSG
      mapping: og:title
    utterances:
      repo: hbstack/site
    twikoo:
      env_id: https://twikoo.hugomods.com/
  footer:
    powered_by: true
    # site_title: HB Framework
    socials:
      github: hbstack
      kofi: razonyang
      paypal: razonyang
      twitter: razonyang
      mastodon: razonyang
      rss: true
  content_panel:
    repo:
      service: github
      repo: hbstack/site
      branch: main
      # subpath: exampleSite
  thanks:
    socials:
      paypal: razonyang
      kofi: razonyang
pwa:
  icon_path: images/logo.png
  icon_sizes: [192, 512]
  offline_image: images/pwa/offline.svg
  precaches:
    - url: /en/
    - url: /zh-hans/
  manifest:
    background_color: '#7952b3'
    theme_color: '#7952b3'
    short_name: 'HB'

seo:
  favicons:
    icon: images/logo.png
    svg_icon: images/logo.svg
    mask_icon: images/logo.svg
    mask_icon_color: '#7952b3'
    sizes:
      - size: 180x180
        rel: apple-touch-icon

code_block_panel:
  max_lines: 8

search:
  min_match_char_length: 1

docsearch:
  app_id: ZUM0MDPYWM
  api_key: 335e389d4a9a43c1774deb2e85ff3494
  index_name: hbstack

hugopress:
  modules:
    hb-custom:
      hooks:
        body-begin:
          cacheable: true
        hb-footer-end:
          cacheable: true
        hb-docs-doc-toc-begin:
          cacheable: true
        hb-docs-doc-toc-end:
          cacheable: true
        hb-blog-post-toc-begin:
          cacheable: true
        hb-blog-post-toc-end:
          cacheable: true
    # search:
    #   disabled: true
    # hb-header-search:
    #   disabled: true
    docsearch:
      disabled: true
    hb-header-docsearch:
      disabled: true
